CONSTRUCT {
    ?x ?y ?z .
    ?z ?w ?v.
    ?z ?m ?n .
    ?v ?a ?b .
}
WHERE {
    #-- we know, it is a document and we get all properties
	?x a <http://ai4bd.com/resource/edm/Document>.
    ?x ?y ?z .
	OPTIONAL {
		#-- get the interpreted content
		?z ?w ?v .
		#-- and if there are some properties
        OPTIONAL {?z ?m ?n }
		#-- get the content of the resource attributes
		OPTIONAL {?v ?a ?b }
		#-- executed first: get all resource attributes but filter the unwanted
		{
		 SELECT  ?v WHERE {
			   ?v a <http://ai4bd.com/resource/gdm/GdmResourceAttribute> .
			   #-- this filter the complete not if it matched a basic graph pattern
               FILTER NOT EXISTS { ?v <http://ai4bd.com/resource/cdm/juzo/numeric/ldl>?b }
		  }
		}
	}
}